# Generated by Django 5.1.3 on 2024-11-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='datetime',
            new_name='date',
        ),
    ]
